### ISSUE TITLE
Github Publish only works the first time

### ISSUE THREAD

**Issue by rallisf1** [primodotso/primo-server#21]
Using primo v1.6.47 server v1.0.0--beta.1

Publishing to github works the first time but it won't push any updates when publishing again. The response is 
```json
{
    "deployment": null,
    "error": null
}
````
`active_deployment` is correctly populated in sites table.

Also a minor bug: In `/src/extensions/Build.svelte`  `let lastDeployment = find($allSites, ['id', siteID])?.['active_deployment']` is wrong as there is no such key. Perhaps it should be `let lastDeployment = find($allSites, ['id', siteID])?.data?.['active_deployment']`?

P.S. I haven't tested this on desktop version, it might work there.

**Comment by mateomorris** [comment]
Thanks, will try to fix this tonight.

**Comment by mateomorris** [comment]
Okay easy fix - just **change the `active_deployment` column in the `sites` table from text to jsonb**. Should work after that, no update needed. But I'll change it in the setup schema for new users. 
![image](https://user-images.githubusercontent.com/39444813/199393853-6247a985-db4f-4fcb-b3df-cffa7e8fec6b.png)

> Also a minor bug: In /src/extensions/Build.svelte let lastDeployment = find($allSites, ['id', siteID])?.['active_deployment'] is wrong as there is no such key. Perhaps it should be let lastDeployment = find($allSites, ['id', siteID])?.data?.['active_deployment']?

Not sure what you mean - items in `$allSites` contain `active_deployment`, not `data`
![image](https://user-images.githubusercontent.com/39444813/199394099-50a4b742-fdf2-4e9a-8259-d100ca2ce8b8.png)
