### ISSUE TITLE
No option to download desktop version?

### ISSUE THREAD

**Issue by ejkreboot** [primodotso/primo-server#29]
The docs and youtube video announcing beta v3 there is mention of a desktop version. The getting started docs mention downloading from primo.so, but I cannot find a download link there. Am I missing something? 

Thank you!

**Comment by mateomorris** [comment]
Heya - I actually took the link off the landing page recently. The plan is to focus on the server version (adding on-page editing, realtime collaboration, framework integrations) and the desktop version adds a lot of work to that; also, most people just seem to be using the server version. But you can still download it from the releases list here: https://github.com/primodotso/primo/releases/tag/v1.0.0-beta.3
